{{- range $index, $value := tuple "kube-master-1" "kube-master-2" "kube-master-3" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: infra-mongo-infra-mongo-{{ $index }}
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ $.Release.Namespace | quote }}
    name: infra-mongo-infra-mongo-{{ $index }}
  local:
    path: /var/lib/compass/db/mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ $value }}
{{- end }}
