{{- range $index, $value := .Values.platformConfig.mongoHosts }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-mongo-infra-mongo-{{ $index }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: infra-mongo-infra-mongo-{{ $index }}
{{- end }}
