{{- range tuple "0" "1" "2" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-mongo-infra-mongo-{{ . }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: infra-mongo-infra-mongo-{{ . }}
{{- end }}
