apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ .Values.serviceName | quote }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ default 1 .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "common.images.image" (dict "context" $ "repository" .Values.platformConfig.imageRepositoryLibrary "imageRoot" .Values.image) | quote }}
        imagePullPolicy: {{ default "Always" .Values.platformConfig.imagePullPolicy | quote }}
        {{- if .Values.command }}
        command: {{- include "common.tplvalues.render" ( dict "value" .Values.command "context" $) | nindent 8 }}
        {{- else }}
        command:
        - "mongod"
        {{- end }}
        {{- if .Values.args }}
        args: {{- include "common.tplvalues.render" ( dict "value" .Values.args "context" $) | nindent 8 }}
        {{- else }}
        args:
        - "--replSet"
        - "rs0"
        - "--bind_ip"
        - "0.0.0.0"
        {{- end }}
        {{- if .Values.serverPort }}
        ports:
        - name: mongo
          containerPort: {{ .Values.serverPort }}
        {{- end }}
        {{- if .Values.resources }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: {{ include "common.names.fullname" . }}
          mountPath: {{ .Values.persistence.mountPath | quote }}
        {{- end }}
      - name: {{ .Chart.Name }}-sidecar
        image: {{ include "common.images.image" (dict "context" $ "repository" .Values.platformConfig.imageRepositoryRelease "imageRoot" .Values.sidecar.image) | quote }}
        imagePullPolicy: {{ default "Always" .Values.platformConfig.imagePullPolicy | quote }}
        env:
        - name: "KUBE_NAMESPACE"
          value: {{ .Release.Namespace | quote }}
        - name: "MONGO_SIDECAR_POD_LABELS"
          value: "app.kubernetes.io/name=infra-mongo"
        - name: "MONGO_PORT"
          value: {{ .Values.serverPort | quote }}
        - name: "KUBERNETES_MONGO_SERVICE_NAME"
          value: {{ .Values.serviceName | quote }}
        {{- if .Values.sidecar.resources }}
        resources: {{- toYaml .Values.sidecar.resources | nindent 10 }}
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "common.names.fullname" . }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      accessModes:
      {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
      {{- end }}
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- end }}
